### ISSUE TITLE
Some original language tags are being crawled and imported

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/anansi#44]
For example, "Ramadi (Iraq)"@43.305845 and "http://en.wikipedia.org/wiki/Kirkuk"@link found in the results for http://acropolis.org.uk/?class=http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23Concept&offset=0 for the entity http://acropolis.org.uk/1043ac1deb1942a99dc5c2acb54b284d#id

Interestingly enough "Ramadi (Iraq)"@43.305845 is not in the results from http://acropolis.org.uk/1043ac1deb1942a99dc5c2acb54b284d.nq but the link to the Russian page is still there:
http://acropolis.org.uk/1043ac1deb1942a99dc5c2acb54b284d#id http://www.w3.org/2000/01/rdf-schema#label "http://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%BC%D0%B0%D0%B4%D0%B8"@link http://acropolis.org.uk/1043ac1deb1942a99dc5c2acb54b284d .

Maybe worth doing some filtering at import time ?

**Comment by nevali** [comment]
This looks like a bug in Spindle's plug-in for Quilt: the @link "language" is nonsense from NYT data, but the @43.305845 is being generated from the results of the PostgreSQL query; I'll open separate issue for that there.

**Comment by nevali** [comment]
Opened as bbcarchdev/spindle#25
