### ISSUE TITLE
Triples with a subject based in http://233a..1280;9a39~20150531t140000z--pt0h30m0s

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/anansi#45]
First set of 2079 resources:
http://acropolis.org.uk/00355946403d45fca3d4d0d835d7e173#id
http://acropolis.org.uk/00de266c33d14d779b704698a75487bd#id
http://acropolis.org.uk/00e43bf6fb0c48ed869b9d5816458abd#id
http://acropolis.org.uk/020df7cb0cd24c798ef0aca021545caa#id
http://acropolis.org.uk/04a9252d50e242dbbd203d8c593e2b49#id
http://acropolis.org.uk/05b984ba29d8424aa02f135f81c7926b#id
http://acropolis.org.uk/05d433083f4b4abbb4d30b178d8a1367#id
http://acropolis.org.uk/081f65d225ce41569f8693d816320ccb#id
http://acropolis.org.uk/084cc13c4b494894871170d3b77d7d02#id
http://acropolis.org.uk/0af6746485264224838cecda48386e48#id

complete list on https://github.com/Dans-labs/RESplorer/blob/master/weird.txt

**Comment by nevali** [comment]
The 4store setup was broken, it's being re-built at the moment — pretty sure this is the cause.

**Comment by nevali** [comment]
(e.g., the first item — `00355946403d45fca3d4d0d835d7e173` — has a completely different broadcast event URI: `dvb://233a..10bf;ff0fe~20150602T190000Z--PT1H0M0S`)

**Comment by nevali** [comment]
Do you want to take a look at things now? It should be a bit healthier...

**Comment by cgueret** [comment]
Yup! No more dvb URIs now :-)

Here is the new output of RESplorer:
Total number of entities :
        91098
Total number of triples :
        {'all': 4236136, 'second': 536216}
Data import chains :
        billings.acropolis.org.uk -> acropolis.org.uk
        rdf.freebase.com -> acropolis.org.uk
        data.nytimes.com -> acropolis.org.uk
        www.bbc.co.uk -> acropolis.org.uk
        fp.bbc.co.uk -> acropolis.org.uk
        sws.geonames.org -> acropolis.org.uk
        sws.geonames.org -> data.nytimes.com
        rdf.insee.fr -> acropolis.org.uk
        www.ordnancesurvey.co.uk -> acropolis.org.uk
        dbpedia.org -> acropolis.org.uk
Instances per type :
        73752 : http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing
        35 : http://rdfs.org/ns/void#Dataset
        10156 : http://www.w3.org/2004/02/skos/core#Concept
        35 : http://purl.org/dc/dcmitype/Collection
        1868 : http://purl.org/vocab/frbr/core#Work
        2186 : http://xmlns.com/foaf/0.1/Document
        3066 : http://purl.org/NET/c4dm/event.owl#Event
Instances per source :
        72217 : sws.geonames.org
        11713 : data.nytimes.com
        88914 : acropolis.org.uk
        5006 : billings.acropolis.org.uk

**Comment by nevali** [comment]
Perfect, that looks a lot healthier :+1:
