### ISSUE TITLE
Handle HTTP/HTTPS licenses

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/anansi#56]
The list of whitelisted licenses should contain the https alternative to all the http version, or Anansi should be able to check the license in a protocol independent way.

**Comment by nevali** [comment]
The license URI is an opaque identifier.

HTTP/HTTPS variants are a deployment-specific issue; the whitelist in the live Research & Education Space setup does contain a number of HTTPS variants (more can be added if there are some missing).
